index:
    path: /
    controller: App\Controller\HomepageController::default

createUser:
    path: /create-user
    controller: App\Controller\UserController::createUser

userList:
    path: /user-list/{page}
    controller: App\Controller\UserController::userList
    defaults:
        page: 1
    requirements:
        page: '\d+'

apiList:
    path: /api-list
    controller: App\Controller\HomepageController::apiList

# Api
createUserApi:
    path: /api/v1/createUser
    controller: App\AppBundle\API\v1\UserController::createUser

userCountApi:
    path: /api/v1/userCount
    controller: App\AppBundle\API\v1\UserController::userCount

userListApi:
    path: /api/v1/userList/{page}
    controller: App\AppBundle\API\v1\UserController::userList
    defaults:
        page: 1
    requirements:
        page: '\d+'

userListAllApi:
    path: /api/v1/userListAll
    controller: App\AppBundle\API\v1\UserController::userListAll

#api:
#    resource: '@AppBundle/Controller/'
#    type: annotation
