createUserApi:
    path: /api/v1/createUser
    controller: App\AppBundle\API\v1\UserController::createUser

userListAllApi:
    path: /api/v1/userListAll
    controller: App\AppBundle\API\v1\UserController::userListAll

userCountApi:
    path: /api/v1/userCount
    controller: App\AppBundle\API\v1\UserController::userCount

userListApi:
    path: /api/v1/userList/{page}
    controller: App\AppBundle\API\v1\UserController::userList
    defaults:
        page: 1
    requirements:
        page: '\d+'
